language: node_js
node_js:
  - stable
install:
  - npm install
script:
  - npm test
  - npm i -g codecov nyc
after_success:
  - nyc npm test && nyc report --reporter=text-lcov > coverage.lcov && codecov
